# Generated by Django 6.0.3 on 2026-04-02 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, verbose_name='소속')),
                ('car_number', models.CharField(max_length=20, verbose_name='차량 번호')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='핸드폰 번호')),
                ('start_date', models.DateField(verbose_name='출입 시작일')),
                ('end_date', models.DateField(verbose_name='출입 종료일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '차량',
                'verbose_name_plural': '차량 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('status', models.CharField(choices=[('waiting', '대기중'), ('entered', '입차'), ('exited', '출차')], default='waiting', max_length=10, verbose_name='상태')),
                ('entered_at', models.DateTimeField(blank=True, null=True, verbose_name='입차 시각')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='출차 시각')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='처리자')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parking.vehicle', verbose_name='차량')),
            ],
            options={
                'verbose_name': '입출차 기록',
                'verbose_name_plural': '입출차 기록 목록',
                'ordering': ['-date'],
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
