# Generated by Django 6.0.3 on 2026-04-03 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KumnareReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='보고 날짜')),
                ('sales_amount', models.PositiveIntegerField(default=0, verbose_name='매출액')),
                ('rental_total_users', models.PositiveIntegerField(default=0, verbose_name='렌탈 총이용객')),
                ('stamp_issued', models.PositiveIntegerField(default=0, verbose_name='스탬프투어 지급')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kumnare_reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '꿈나래마켓 보고서',
                'verbose_name_plural': '꿈나래마켓 보고서 목록',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KumnareRentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='품목명')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='수량')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='facilities.kumnarereport', verbose_name='보고서')),
            ],
            options={
                'verbose_name': '렌탈 품목',
                'verbose_name_plural': '렌탈 품목 목록',
                'ordering': ['order'],
            },
        ),
    ]
