# Generated by Django 6.0.3 on 2026-04-03 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_eoulrimreport_eoulrimnewmenuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JamjamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='보고 날짜')),
                ('daily_net_sales', models.PositiveIntegerField(default=0, verbose_name='당일 순매출(원)')),
                ('customer_count', models.PositiveIntegerField(default=0, verbose_name='객수(명)')),
                ('notes', models.TextField(blank=True, verbose_name='매출증감사유 및 특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jamjam_reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '잼잼카페 보고서',
                'verbose_name_plural': '잼잼카페 보고서 목록',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JamjamNewMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='판매수량')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_menu_items', to='facilities.jamjamreport', verbose_name='보고서')),
            ],
            options={
                'verbose_name': '신메뉴 판매',
                'verbose_name_plural': '신메뉴 판매 목록',
                'ordering': ['order'],
            },
        ),
    ]
