# Generated by Django 6.0.3 on 2026-04-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(choices=[('all', '중앙일보'), ('parking', '주차 관리'), ('info', '안내센터'), ('operations', '운영사무국'), ('facilities', '편의시설')], default='operations', max_length=20, verbose_name='소속'),
        ),
    ]
