# Generated by Django 6.0.3 on 2026-04-02 04:55

from django.db import migrations, models


def convert_all_to_operations(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(organization='all').update(organization='operations')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization'),
    ]

    operations = [
        migrations.RunPython(convert_all_to_operations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(choices=[('operations', '운영사무국'), ('parking', '주차 관리'), ('info', '안내센터'), ('facilities', '편의시설')], default='operations', max_length=20, verbose_name='소속'),
        ),
    ]
