# Generated by Django 6.0.3 on 2026-04-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unify_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', '직원'), ('up_staff', '운영사무국직원'), ('manager', '관리자')], default='staff', max_length=10, verbose_name='역할'),
        ),
    ]
