# Generated by Django 6.0.3 on 2026-04-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(choices=[('operations', '운영사무국'), ('parking', '보안팀'), ('info', '안내센터'), ('sportsfield', '스포츠필드'), ('dreammarket', '꿈나래마켓'), ('eulrimcafe', '카페어울림'), ('jemjemcafe', '잼잼카페')], default='operations', max_length=20, verbose_name='소속'),
        ),
    ]
