# Generated by Django 6.0.3 on 2026-04-01 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='보고 날짜')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('submitted', '제출완료')], default='draft', max_length=10, verbose_name='상태')),
                ('completed_tasks', models.TextField(blank=True, verbose_name='금일 완료 업무')),
                ('in_progress_tasks', models.TextField(blank=True, verbose_name='진행 중 업무')),
                ('tomorrow_tasks', models.TextField(blank=True, verbose_name='내일 예정 업무')),
                ('issues', models.TextField(blank=True, verbose_name='이슈 및 특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '일일 업무보고서',
                'verbose_name_plural': '일일 업무보고서 목록',
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('author', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('completed', '완료'), ('in_progress', '진행중'), ('tomorrow', '예정')], max_length=15, verbose_name='분류')),
                ('content', models.CharField(max_length=500, verbose_name='업무 내용')),
                ('progress', models.IntegerField(default=0, verbose_name='진행률(%)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='reports.dailyreport', verbose_name='보고서')),
            ],
            options={
                'verbose_name': '업무 항목',
                'verbose_name_plural': '업무 항목 목록',
                'ordering': ['order'],
            },
        ),
    ]
