# Generated by Django 6.0.3 on 2026-04-02 07:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='업무 시작일자')),
                ('task_name', models.CharField(max_length=300, verbose_name='업무명')),
                ('progress', models.IntegerField(default=0, verbose_name='진행도(%)')),
                ('status', models.CharField(choices=[('doing', '진행중'), ('hold', '보류'), ('done', '완료')], default='doing', max_length=10, verbose_name='상태')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '일일 업무',
                'verbose_name_plural': '일일 업무 목록',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
