# Generated by Django 6.0.3 on 2026-04-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_daily_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(unique=True, verbose_name='보고 날짜')),
                ('today_total', models.PositiveIntegerField(default=0, verbose_name='금일 입장 총수')),
                ('main_gate_walk', models.PositiveIntegerField(default=0, verbose_name='주출입구 도보')),
                ('sub_gate_walk', models.PositiveIntegerField(default=0, verbose_name='부출입구 도보')),
                ('car_visit', models.PositiveIntegerField(default=0, verbose_name='차량방문')),
                ('yesterday_total', models.PositiveIntegerField(default=0, verbose_name='전일 입장 총수')),
                ('tomorrow_temp_min', models.IntegerField(default=0, verbose_name='명일 기온 최저(°)')),
                ('tomorrow_temp_max', models.IntegerField(default=0, verbose_name='명일 기온 최고(°)')),
                ('tomorrow_rain_pct', models.PositiveIntegerField(default=0, verbose_name='명일 강수확률(%)')),
                ('facility_interior', models.TextField(blank=True, verbose_name='내부시설')),
                ('facility_outdoor', models.TextField(blank=True, verbose_name='잔디마당·가로수길·전망언덕')),
                ('facility_fountain', models.TextField(blank=True, verbose_name='분수정원·잼잼카페')),
                ('parking_family', models.PositiveIntegerField(default=0, verbose_name='다둥이')),
                ('parking_disabled', models.PositiveIntegerField(default=0, verbose_name='장애인')),
                ('parking_pregnant', models.PositiveIntegerField(default=0, verbose_name='임산부')),
                ('parking_children', models.PositiveIntegerField(default=0, verbose_name='어린이단체')),
                ('internal_event', models.TextField(blank=True, verbose_name='내부행사/프로그램')),
                ('external_event', models.TextField(blank=True, verbose_name='외부행사')),
                ('special_notes', models.TextField(blank=True, verbose_name='특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '일일보고 운영데이터',
                'verbose_name_plural': '일일보고 운영데이터 목록',
                'ordering': ['-report_date'],
            },
        ),
    ]
