# Generated by Django 6.0.3 on 2026-04-15 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_dailytask_completed_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='is_reviewed',
            field=models.BooleanField(default=False, verbose_name='검토 완료'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토 일시'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
    ]
