# Generated by Django 6.0.3 on 2026-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_task_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdailydata',
            name='godata_total',
            field=models.PositiveIntegerField(default=0, verbose_name='GODATA 도보 합계'),
        ),
    ]
