# Generated by Django 6.0.3 on 2026-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_operationsdailydata_godata_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_0900_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='09:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_0900_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='09:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1000_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1000_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1100_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='11:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1100_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='11:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1200_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='12:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1200_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='12:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1300_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='13:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1300_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='13:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1400_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='14:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1400_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='14:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1500_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='15:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1500_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='15:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1600_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='16:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1600_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='16:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1700_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='17:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1700_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='17:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1800_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='18:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1800_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='18:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1900_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='19:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1900_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='19:00 부출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_2000_main',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='20:00 주출입구'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_2000_sub',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='20:00 부출입구'),
        ),
    ]
