# Generated by Django 6.0.3 on 2026-05-13 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_add_timeslot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdailydata',
            name='facility_interior_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='내부시설 작업사진 캡션'),
        ),
        migrations.CreateModel(
            name='FacilityWorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_photos/%Y/%m/', verbose_name='사진')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to='reports.operationsdailydata', verbose_name='일일보고')),
            ],
            options={
                'verbose_name': '내부시설 작업사진',
                'verbose_name_plural': '내부시설 작업사진 목록',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='행사명')),
                ('columns_json', models.JSONField(blank=True, default=list, verbose_name='컬럼')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_events', to='reports.operationsdailydata', verbose_name='일일보고')),
            ],
            options={
                'verbose_name': '내부행사/프로그램',
                'verbose_name_plural': '내부행사/프로그램 목록',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
