# Generated by Django 6.0.3 on 2026-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_operationsdailydata_facility_interior_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdailydata',
            name='manual_eoulrim_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='카페어울림 수기매출'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='manual_jamjam_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='잼잼카페 수기매출'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='manual_kumnare_sales',
            field=models.PositiveIntegerField(default=0, verbose_name='꿈나래마켓 수기매출'),
        ),
    ]
