# Generated by Django 6.0.3 on 2026-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_operationsdailydata_manual_eoulrim_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdailydata',
            name='manual_rental_total',
            field=models.PositiveIntegerField(default=0, verbose_name='대여물품 수기 인원'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='manual_shuttle_total',
            field=models.PositiveIntegerField(default=0, verbose_name='셔틀버스 수기 인원'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='manual_stamp_total',
            field=models.PositiveIntegerField(default=0, verbose_name='스탬프투어 수기 인원'),
        ),
    ]
