# Generated by Django 6.0.3 on 2026-05-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_operationsdailydata_manual_rental_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityworkphoto',
            options={'ordering': ['category', 'order', 'created_at'], 'verbose_name': '운영관리 작업사진', 'verbose_name_plural': '운영관리 작업사진 목록'},
        ),
        migrations.AddField(
            model_name='facilityworkphoto',
            name='category',
            field=models.CharField(choices=[('interior', '내부시설'), ('outdoor', '잔디마당·가로수길·전망언덕'), ('fountain', '분수정원·잼잼카페')], default='interior', max_length=10, verbose_name='구역'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='facility_fountain_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='분수정원·잼잼카페 작업사진 캡션'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='facility_outdoor_caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='잔디마당·가로수길·전망언덕 작업사진 캡션'),
        ),
    ]
