# Generated by Django 6.0.3 on 2026-05-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_facilityworkphoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='행사명')),
                ('columns_json', models.JSONField(blank=True, default=list, verbose_name='컬럼')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_events', to='reports.operationsdailydata', verbose_name='일일보고')),
            ],
            options={
                'verbose_name': '외부행사',
                'verbose_name_plural': '외부행사 목록',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
