# Generated by Django 6.0.3 on 2026-05-18 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_externalevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', '연차'), ('half', '반차'), ('quarter', '반반차'), ('sick', '병가'), ('etc', '기타')], max_length=10, verbose_name='휴가 종류')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('half_period', models.CharField(blank=True, choices=[('am', '오전'), ('pm', '오후')], max_length=2, verbose_name='반차/반반차 시간대')),
                ('reason', models.TextField(blank=True, verbose_name='사유')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=10, verbose_name='상태')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토 일시')),
                ('review_comment', models.TextField(blank=True, verbose_name='검토 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_vacations', to=settings.AUTH_USER_MODEL, verbose_name='검토자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '휴가 신청',
                'verbose_name_plural': '휴가 신청 목록',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutyShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='근무일')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_duties', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_shifts', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '당직 근무',
                'verbose_name_plural': '당직 근무 목록',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
