# Generated by Django 6.0.3 on 2026-06-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_vacationrequest_dutyshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='완료 일자'),
        ),
    ]
