# Generated by Django 6.0.3 on 2026-06-12 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_subtask_completed_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LadderGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('players', models.JSONField(default=list, verbose_name='참가자')),
                ('results', models.JSONField(default=list, verbose_name='결과')),
                ('rungs', models.JSONField(default=list, verbose_name='가로줄(ROWS x N-1)')),
                ('revealed', models.JSONField(default=dict, verbose_name='공개된 결과 {start_col: end_col}')),
                ('is_active', models.BooleanField(default=True, verbose_name='진행중')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ladder_games', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '사다리 게임',
                'verbose_name_plural': '사다리 게임 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
