# Generated by Django 6.0.3 on 2026-06-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_laddergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='hold_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='보류 시작일자'),
        ),
    ]
