# Generated by Django 6.0.3 on 2026-08-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_dailytask_hold_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsdailydata',
            name='rear_gate_walk',
            field=models.PositiveIntegerField(default=0, verbose_name='후문주차장 도보'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_0900_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='09:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1000_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='10:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1100_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='11:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1200_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='12:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1300_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='13:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1400_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='14:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1500_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='15:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1600_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='16:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1700_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='17:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1800_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='18:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_1900_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='19:00 후문주차장'),
        ),
        migrations.AddField(
            model_name='operationsdailydata',
            name='slot_2000_rear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='20:00 후문주차장'),
        ),
    ]
