# Generated by Django 6.0.3 on 2026-04-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('baseball', '어린이 야구장'), ('soccer', '축구장'), ('tennis_grass', '테니스장 잔디코트'), ('tennis_hard', '테니스장 하드코트')], max_length=20)),
                ('reservation_date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('applicant_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('confirmed', '예약완료'), ('cancelled', '예약취소')], max_length=20)),
                ('rv_no', models.IntegerField(unique=True)),
                ('scraped_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['reservation_date', 'time_start'],
            },
        ),
    ]
