# Generated by Django 6.0.3 on 2026-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsfield', '0007_usage_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsfieldentry',
            name='category',
            field=models.CharField(choices=[('normal', '일반'), ('quarter', '쿼터'), ('event', '행사'), ('other', '기타')], max_length=20),
        ),
    ]
