# Generated by Django 6.0.3 on 2026-04-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='보고 날짜')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('submitted', '제출완료')], default='draft', max_length=10, verbose_name='상태')),
                ('info_stroller', models.TextField(blank=True, verbose_name='유모차/휠체어 대여')),
                ('info_nulbom', models.TextField(blank=True, verbose_name='늘봄프로그램')),
                ('info_note', models.TextField(blank=True, verbose_name='인포메이션 특이사항')),
                ('shuttle_maintenance', models.TextField(blank=True, verbose_name='차량 유지보수')),
                ('shuttle_total', models.PositiveIntegerField(default=0, verbose_name='셔틀 총원')),
                ('patrol_facility', models.TextField(blank=True, verbose_name='시설점검 및 청결확인')),
                ('patrol_sports', models.TextField(blank=True, verbose_name='스포츠필드 관리 및 자판기 점검,순찰')),
                ('patrol_note', models.TextField(blank=True, verbose_name='순찰 특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_reports', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '안내센터 보고서',
                'verbose_name_plural': '안내센터 보고서 목록',
                'ordering': ['-report_date', '-created_at'],
                'unique_together': {('author', 'report_date')},
            },
        ),
    ]
