# Generated by Django 6.0.3 on 2026-04-02 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inforeport',
            name='info_nulbom',
        ),
        migrations.RemoveField(
            model_name='inforeport',
            name='info_stroller',
        ),
        migrations.RemoveField(
            model_name='inforeport',
            name='patrol_facility',
        ),
        migrations.RemoveField(
            model_name='inforeport',
            name='patrol_sports',
        ),
        migrations.RemoveField(
            model_name='inforeport',
            name='shuttle_maintenance',
        ),
        migrations.CreateModel(
            name='InfoReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('info', '인포메이션'), ('shuttle', '셔틀'), ('patrol', '순찰')], max_length=10, verbose_name='섹션')),
                ('content', models.CharField(max_length=500, verbose_name='업무 내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='info.inforeport', verbose_name='보고서')),
            ],
            options={
                'verbose_name': '안내센터 업무 항목',
                'verbose_name_plural': '안내센터 업무 항목 목록',
                'ordering': ['section', 'order'],
            },
        ),
    ]
